### ISSUE TITLE
Link to development APK is broken

### ISSUE THREAD

**Issue by sanjayankur31** [fedora-infra/mobile#37]
Hi,

I clicked the link on fedoraproject.org/mobile to get the APK but got a 404 instead. 

http://jenkins.cloud.fedoraproject.org/job/fedora-mobile/ws/target/fedora-mobile-0.1.apk

Thanks,
Ankur

**Comment by sanjayankur31** [comment]
http://jenkins.cloud.fedoraproject.org/job/fedora-mobile/ws/ is empty. I'm not sure where to find the built APK :(

**Comment by siwinski** [comment]
The link is pointing to the workspace which is the most current build.  There hasn't been a successful build since #234 (May 22, 2014 5:08:52 AM).  Perhaps update the Jenkins job to save the build artifacts (apk and docs) and then update the links to point to whichever version you want downloaded from fedoraproject.org/mobile?

**Comment by relrod** [comment]
Thanks for the report - this is fixed now.

I got asked to move to a new jenkins slave because the old one was on an EOL Fedora version, but the new one was never set up correctly to build Mobile…

I am going to add in Travis CI support too, and make Travis ship the latest APK to S3 or something, as a backup. Then the app can use a da.gd shorturl (which I have control over) or something, so that if something happens, I can just flip the URL to point to S3.

Or if it ends up working better, we can just stop using Jenkins to build these APKs and flip to Travis+S3 altogether. This would have no net cost, and possibly a [net gain](https://aws.amazon.com/s3/sla/).
